app:
  name: "backend"
  port: "8000"

database:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: ""  #写到了.env文件中
  name: "mychat"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: "" #写到了.env文件中
  db: 0
