syntax = "proto3";
option go_package = "./AIResponse";

package AIResponse;

service Greeter {
    rpc AIResponse (AIStreamRequest) returns (stream AIStreamResponseReply);
    rpc planExecutorResponse (AIStreamRequest) returns (stream planExecutorReply);
}

// 普通AI响应请求
message AIStreamRequest {
    string model = 1;
    string apiKey = 2;
    string baseUrl = 3;
    float temperature = 4;
    int32 maxTokens = 5;
    float topP = 6;
    float frequencyPenalty = 7;
    repeated Message messageHistory = 8;
}

message Message {
    string role = 1;
    string content = 2;
    string fileType = 3;
    string fileUrl = 4;
    string fileContent = 5;
}

message AIStreamResponseReply {
    string content = 1;
}

message planExecutorReply {
    string content = 1;
    string process = 2;
}