// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: AIResponse.proto

package AIResponse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIStreamRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey           string                 `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	BaseUrl          string                 `protobuf:"bytes,3,opt,name=baseUrl,proto3" json:"baseUrl,omitempty"`
	Temperature      float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens        int32                  `protobuf:"varint,5,opt,name=maxTokens,proto3" json:"maxTokens,omitempty"`
	TopP             float32                `protobuf:"fixed32,6,opt,name=topP,proto3" json:"topP,omitempty"`
	FrequencyPenalty float32                `protobuf:"fixed32,7,opt,name=frequencyPenalty,proto3" json:"frequencyPenalty,omitempty"`
	MessageHistory   []*Message             `protobuf:"bytes,8,rep,name=messageHistory,proto3" json:"messageHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AIStreamRequest) Reset() {
	*x = AIStreamRequest{}
	mi := &file_AIResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIStreamRequest) ProtoMessage() {}

func (x *AIStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AIResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIStreamRequest.ProtoReflect.Descriptor instead.
func (*AIStreamRequest) Descriptor() ([]byte, []int) {
	return file_AIResponse_proto_rawDescGZIP(), []int{0}
}

func (x *AIStreamRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIStreamRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AIStreamRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AIStreamRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AIStreamRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AIStreamRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *AIStreamRequest) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *AIStreamRequest) GetMessageHistory() []*Message {
	if x != nil {
		return x.MessageHistory
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileContent   string                 `protobuf:"bytes,5,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_AIResponse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_AIResponse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_AIResponse_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Message) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Message) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

type AIStreamResponseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIStreamResponseReply) Reset() {
	*x = AIStreamResponseReply{}
	mi := &file_AIResponse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIStreamResponseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIStreamResponseReply) ProtoMessage() {}

func (x *AIStreamResponseReply) ProtoReflect() protoreflect.Message {
	mi := &file_AIResponse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIStreamResponseReply.ProtoReflect.Descriptor instead.
func (*AIStreamResponseReply) Descriptor() ([]byte, []int) {
	return file_AIResponse_proto_rawDescGZIP(), []int{2}
}

func (x *AIStreamResponseReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_AIResponse_proto protoreflect.FileDescriptor

const file_AIResponse_proto_rawDesc = "" +
	"\n" +
	"\x10AIResponse.proto\x12\n" +
	"AIResponse\"\x96\x02\n" +
	"\x0fAIStreamRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06apiKey\x18\x02 \x01(\tR\x06apiKey\x12\x18\n" +
	"\abaseUrl\x18\x03 \x01(\tR\abaseUrl\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1c\n" +
	"\tmaxTokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x12\n" +
	"\x04topP\x18\x06 \x01(\x02R\x04topP\x12*\n" +
	"\x10frequencyPenalty\x18\a \x01(\x02R\x10frequencyPenalty\x12;\n" +
	"\x0emessageHistory\x18\b \x03(\v2\x13.AIResponse.MessageR\x0emessageHistory\"\x92\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12!\n" +
	"\ffile_content\x18\x05 \x01(\tR\vfileContent\"1\n" +
	"\x15AIStreamResponseReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2Y\n" +
	"\aGreeter\x12N\n" +
	"\n" +
	"AIResponse\x12\x1b.AIResponse.AIStreamRequest\x1a!.AIResponse.AIStreamResponseReply0\x01B\x0eZ\f./AIResponseb\x06proto3"

var (
	file_AIResponse_proto_rawDescOnce sync.Once
	file_AIResponse_proto_rawDescData []byte
)

func file_AIResponse_proto_rawDescGZIP() []byte {
	file_AIResponse_proto_rawDescOnce.Do(func() {
		file_AIResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AIResponse_proto_rawDesc), len(file_AIResponse_proto_rawDesc)))
	})
	return file_AIResponse_proto_rawDescData
}

var file_AIResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AIResponse_proto_goTypes = []any{
	(*AIStreamRequest)(nil),       // 0: AIResponse.AIStreamRequest
	(*Message)(nil),               // 1: AIResponse.Message
	(*AIStreamResponseReply)(nil), // 2: AIResponse.AIStreamResponseReply
}
var file_AIResponse_proto_depIdxs = []int32{
	1, // 0: AIResponse.AIStreamRequest.messageHistory:type_name -> AIResponse.Message
	0, // 1: AIResponse.Greeter.AIResponse:input_type -> AIResponse.AIStreamRequest
	2, // 2: AIResponse.Greeter.AIResponse:output_type -> AIResponse.AIStreamResponseReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AIResponse_proto_init() }
func file_AIResponse_proto_init() {
	if File_AIResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AIResponse_proto_rawDesc), len(file_AIResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AIResponse_proto_goTypes,
		DependencyIndexes: file_AIResponse_proto_depIdxs,
		MessageInfos:      file_AIResponse_proto_msgTypes,
	}.Build()
	File_AIResponse_proto = out.File
	file_AIResponse_proto_goTypes = nil
	file_AIResponse_proto_depIdxs = nil
}
