// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: fileParsing.proto

package fileParsing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_fileParsing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileParsing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_fileParsing_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_fileParsing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileParsing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_fileParsing_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_fileParsing_proto protoreflect.FileDescriptor

const file_fileParsing_proto_rawDesc = "" +
	"\n" +
	"\x11fileParsing.proto\x12\vfileParsing\"!\n" +
	"\rUploadRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"*\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2V\n" +
	"\vFileParsing\x12G\n" +
	"\n" +
	"UploadFile\x12\x1a.fileParsing.UploadRequest\x1a\x1b.fileParsing.UploadResponse\"\x00B#Z!backend/utils/grpc/pb/fileParsingb\x06proto3"

var (
	file_fileParsing_proto_rawDescOnce sync.Once
	file_fileParsing_proto_rawDescData []byte
)

func file_fileParsing_proto_rawDescGZIP() []byte {
	file_fileParsing_proto_rawDescOnce.Do(func() {
		file_fileParsing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileParsing_proto_rawDesc), len(file_fileParsing_proto_rawDesc)))
	})
	return file_fileParsing_proto_rawDescData
}

var file_fileParsing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fileParsing_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: fileParsing.UploadRequest
	(*UploadResponse)(nil), // 1: fileParsing.UploadResponse
}
var file_fileParsing_proto_depIdxs = []int32{
	0, // 0: fileParsing.FileParsing.UploadFile:input_type -> fileParsing.UploadRequest
	1, // 1: fileParsing.FileParsing.UploadFile:output_type -> fileParsing.UploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileParsing_proto_init() }
func file_fileParsing_proto_init() {
	if File_fileParsing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileParsing_proto_rawDesc), len(file_fileParsing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileParsing_proto_goTypes,
		DependencyIndexes: file_fileParsing_proto_depIdxs,
		MessageInfos:      file_fileParsing_proto_msgTypes,
	}.Build()
	File_fileParsing_proto = out.File
	file_fileParsing_proto_goTypes = nil
	file_fileParsing_proto_depIdxs = nil
}
