// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: fileParsing.proto

package fileParsing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileParsing_UploadFile_FullMethodName = "/fileParsing.FileParsing/UploadFile"
)

// FileParsingClient is the client API for FileParsing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type FileParsingClient interface {
	UploadFile(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type fileParsingClient struct {
	cc grpc.ClientConnInterface
}

func NewFileParsingClient(cc grpc.ClientConnInterface) FileParsingClient {
	return &fileParsingClient{cc}
}

func (c *fileParsingClient) UploadFile(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, FileParsing_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileParsingServer is the server API for FileParsing service.
// All implementations must embed UnimplementedFileParsingServer
// for forward compatibility.
//
// 定义服务
type FileParsingServer interface {
	UploadFile(context.Context, *UploadRequest) (*UploadResponse, error)
	mustEmbedUnimplementedFileParsingServer()
}

// UnimplementedFileParsingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileParsingServer struct{}

func (UnimplementedFileParsingServer) UploadFile(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileParsingServer) mustEmbedUnimplementedFileParsingServer() {}
func (UnimplementedFileParsingServer) testEmbeddedByValue()                     {}

// UnsafeFileParsingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileParsingServer will
// result in compilation errors.
type UnsafeFileParsingServer interface {
	mustEmbedUnimplementedFileParsingServer()
}

func RegisterFileParsingServer(s grpc.ServiceRegistrar, srv FileParsingServer) {
	// If the following call pancis, it indicates UnimplementedFileParsingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileParsing_ServiceDesc, srv)
}

func _FileParsing_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileParsingServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileParsing_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileParsingServer).UploadFile(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileParsing_ServiceDesc is the grpc.ServiceDesc for FileParsing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileParsing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileParsing.FileParsing",
	HandlerType: (*FileParsingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _FileParsing_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fileParsing.proto",
}
